#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-ReadSXC
version:      0.03
version_from: ReadSXC.pm
installdirs:  site
requires:
    Archive::Zip:                  0
    XML::Parser::Lite::Tree:       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
